### PR TITLE
Continues deployment implemented #5

### LINKED ISSUE #5: Setup CI and continuous deployment
Setup [circleci](https://circleci.com/) CI and make sure the resulting website is deployed on GH and accessible via https://status-im.github.io/status-components

### PR DESCRIPTION
**Pull request by rsercano**
Hello,

I was approved as worker of #5, this PR resolves #5, here're the steps to make it work for this repo;

1. Create a deploy key for github; 
`ssh-keygen -m PEM -t rsa -C "ozdemirsercan27@gmail.com"`  (without passphrase and use same email with your github)
2. Go to https://github.com/status-im/status-components/settings/keys, and click “**Add deploy key**”. Enter a title in the “**Title**” field, then copy and paste the public key you created in step 1. Check “Allow write access”, then click “**Add key**”.
3. Go to https://circleci.com/gh/status-im/status-components/edit#ssh (make sure you're using correct URL :) ), and add the key you created in step 1. In the “**Hostname**” field, enter “**github.com**”, and press the submit button
4. Change **line 35** in **.circleci/config.yml** with your email and username. Change fingerprint at **line 39** with the fingerprint which you've got from cicleci.com at step 3.

Let me know for any issue you've encountered

### CODE REVIEW

**Comment by rsercano** [comment]
You may want to squash commits before you merge, was testing a lot.

**Comment by jeluard** [comment]
Actually can you squash the commits yourself? I can't do it in your repo.

Do you have a URL where I can see the result?

**Comment by rsercano** [comment]
Of course; here you go; https://rsercano.github.io/status-components/ 
And here's the circleci; https://circleci.com/gh/rsercano/status-components

For the squash; I suppose there should be an option while merging in [github](https://help.github.com/en/articles/merging-a-pull-request) for that

**Comment by jeluard** [comment]
@rsercano Please squash the commit so that you can choose the commit comment yourself :) Then you can just force push the branch.

**Comment by rsercano** [comment]
Done @jeluard sorry for the inconvenience :/

**Comment by jeluard** [comment]
@rsercano I will look at it today. In the meantime could you squash your commits?

**Comment by rsercano** [comment]
> @rsercano I will look at it today. In the meantime could you squash your commits?

Of course @jeluard thank you

**Comment by rsercano** [comment]
Working on multiple workspaces so GPG signing is a terrible head-ache for me, sorry about that but now it should be fixed.

**Comment by jeluard** [comment]
Please don't sign, not needed for this repo

**Comment by rsercano** [comment]
Aight, do you want me to rebase again ? @jeluard

**Comment by jeluard** [comment]
Please, somehow there are 3 commits in your PR.

**Comment by rsercano** [comment]
Please check #8

**Pull request closed without merging**
