### PR TITLE
#5 circleci ci & cd setup

### LINKED ISSUE #5: Setup CI and continuous deployment
Setup [circleci](https://circleci.com/) CI and make sure the resulting website is deployed on GH and accessible via https://status-im.github.io/status-components

### PR DESCRIPTION
**Pull request by rsercano**
Please ignore #7, I just wanted to get rid of this mess and created this PR @jeluard 

resolves #5

### CODE REVIEW

**Comment by rsercano** [comment]
Do I need to change anything for gitcoin ? I just recreated this PR. @jeluard

**Comment by rsercano** [comment]
Did you have a chance to take a look at this ? @jeluard Sorry to bug you, but this weekend I'm planning to go out of town and this bounty is what I need :) that's because I'm rushing a bit :/

**Comment by jeluard** [comment]
@jakubgs Can you setup the repo as detailed in #7 ?
Do we have an ssh key already maybe?

Also do we have a circleci account ?

**Comment by jakubgs** [comment]
Why circleci? Can you please explain to me what the outcome is supposed to be?

**Comment by jeluard** [comment]
This is a library that will be develop by the community that needs full visibility and simplicity from circleci.

No need for Jenkins here

@jakubgs Can you provide me the right github info?

**Comment by jakubgs** [comment]
>Can you provide me the right github info?

What do you need though? I can see you are an admin in this repo so you should have access to https://github.com/status-im/status-components/settings/keys. What else do you need?

**Comment by jeluard** [comment]
I was assuming we already add those things shared somewhere? Or I can just go ahead and create a new key?

**Comment by jakubgs** [comment]
Compartmentalization is always good. I'd rather not use the key Jenkins uses connected to our whole org for a project that will use a separate CI. I'd be in favor of adding a new key.

**Comment by jeluard** [comment]
@jakubgs What I need though is access to the `status-im` circleci account to add this key, unless there is one added already? I can see some existing project here.

**Comment by jakubgs** [comment]
>I can see some existing project here.

I have no idea what that is. I've never used CircleCI and I don't have any credentials for it.

**Comment by rsercano** [comment]
It should actually be a github login..

**Comment by jeluard** [comment]
@rsercano Merging to make sure you can enjoy margaritas this weekend :) I might need your help later on?

@StatusSceptre Can you deliver the bounty?

**Comment by rsercano** [comment]
Of course, thank you so much @jeluard I'm open to talk anytime, in fact you may add me on skype; **rsercanozdemir** and reach me anytime

**Comment by rsercano** [comment]
I suppose [it's working now](http://circleci.com/gh/status-im/status-components) @jeluard ? :) Would you please release the bounty @StatusSceptre ?

**Comment by rsercano** [comment]
ping @StatusSceptre

**Pull request merged**
